# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('undergradInstittute', models.TextField()),
                ('undergradDegree', models.CharField(max_length=255)),
                ('undergradBranch', models.CharField(max_length=50)),
                ('undergradGPA', models.FloatField()),
                ('GREScore', models.IntegerField()),
                ('GMATScore', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationUniversity', models.CharField(max_length=255)),
                ('applicationStatus', models.CharField(choices=[('Applied', 'Applied'), ('Admit', 'Admit'), ('Reject', 'Reject')], max_length=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSPHDDataAggregator.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='AwardsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSPHDDataAggregator.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSPHDDataAggregator.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSPHDDataAggregator.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='SocialWorkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialWork', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSPHDDataAggregator.Applicant')),
            ],
        ),
    ]
